[package]
name = "gadgetdisk-usb"
description = "configfs 读写、UDC 选择、mass_storage 编排与 USB 身份配置"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
gadgetdisk-proto.workspace = true
libc.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
